### ISSUE TITLE
Unable to see the admin console - solved, sort of

### ISSUE THREAD

**Issue by AaronRobinson** [jboss-dockerfiles/wildfly#9] opened 2014-12-28 10:42 UTC
I was having a hard time connecting the the console but sort of solved it, except for one thing. I thought this might help others. There are a couple of things that still don't work/I don't understand, so would be useful to me to get answers for those.

I'm trying to run the latest wildfly 8.2 in a container running on a Mac, so using boot2docker.

I've followed the instructions in https://github.com/jboss-dockerfiles/wildfly/blob/master/README.md and built a new image, adding the following as instructed

FROM jboss/wildfly
RUN /opt/jboss/wildfly/bin/add-user.sh admin admin --silent

I then start the container using 
docker run -it -p8080:8080 -p 9990:9990 jboss/wildfly-admin

And then access the app as instructed, but get "This webpage is not available" http://192.168.59.103:9090 and http://192.168.59.103:9090/console
http://192.168.59.103:8080 is fine, but the link to admin console fails with unable to redirect, suggesting the interface the admin console is running on is different

The suggestion in https://github.com/jboss-dockerfiles/wildfly/issues/3 is to bind the management interfaces to 0.0.0.0 like this
docker run -it -p 8123:8080 -p 9123:9990 jboss/wildfly-custom /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0 -Djboss.management.http.port=8124
NOTE, this also moves from me using standalone.sh to using domain.sh and it also adds -Djboss.management.http.port=8124

This gives me "No Console Active - The server configuration does not appear to have an active console. If you are running a standalone server check the http interface is enabled in the standalone.xml configuration, if you are running a domain the http interface can not be automatically detected so check the host.xml configuration and connect directly."

I try changing the 0.0.0.0 interface above to the boot2docker VM address, 192.168.59.103, but this results in errors on start up so I reverted to 0.0.0.0

[Host Controller] 09:54:07,065 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.network.management: org.jboss.msc.service.StartException in service jboss.network.management: JBAS015810: failed to resolve interface management
[Host Controller] 	at org.jboss.as.server.services.net.NetworkInterfaceService.start(NetworkInterfaceService.java:96) [wildfly-server-8.2.0.Final.jar:8.2.0.Final]
[Host Controller] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
[Host Controller] 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881) [jboss-msc-1.2.2.Final.jar:1.2.2.Final]
[Host Controller] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_65]
[Host Controller] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_65]
[Host Controller] 	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_65]

I then moved back from domain.sh to standalone.sh and removed the -Djboss.management.http.port=8124, so 
$ docker run -it -p 8080:8080 -p 9990:9990 jboss/wildfly-admin /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
and I can now access the app at 8080 and the console via the link from the app and directly on 9990

I can add the -Djboss.management.http.port=xxxx back in but the port must match the one specified on the docker run command -p 9990:9990. If I try an other I get a 404

Switching back to domain.sh, I can also access the console but only directly. I can't access it via the link on the page at 8080. 

It suggests "if you are running a domain the http interface can not be automatically detected so check the host.xml configuration and connect directly."

This is not clear to me but there is a property in host.xml that matches -Djboss.management.http.port which looks like it defaults to 9990, so looks correct. There are references to bins addresses but we're already specifying these on the docker run command line so I'm really not sure what needs to change here.

I hope this helps others to connect to the console.

Be good to know what is meant by that message though so we know what to change in the host.xml file.

**Comment by sherl0cks** [comment] 2015-02-17 05:17
@goldmann  - After reading through this issue, #3 and #8 I think it's clear that the most confusing thing about this Dockerfile is the decision to not expose the management console. So my question is what is the purpose of this Dockerfile? If it's simply to get people up and running with Wildfly and Docker (which is what is seems), then it seems like binding the management console with the default command is just logical - one of those things that should just work. If there is some other purpose, then we need to get the README updated to reflect that. Happy to send a pull request to that end.

**Comment by goldmann** [comment] 2015-02-20 09:42
Hiya!

Sorry for late response. The admin console is not exposed since it's not exposed by the default launch command. The idea is that we do not expose anything but necessary. Many people will not use the console at all (using this image just as a container where they deploy the app). Having exposed console there doesn't make sense. But yes, README.md needs to be updated to reflect this :)

**Comment by zshamrock** [comment] 2015-02-21 12:18
Hello, @goldmann but how do you then configure the resources/modules necessary for your application? You build the new docker image based on the setup is required for your application (configuring datasource, jndi, messaging, etc.)? (using ADD command?) Do I understand this correctly?

More broader question - so Docker is not about for simplify local development (which it can do), but for stable reproducible deployment of the self contained image?

**Comment by goldmann** [comment] 2015-02-21 13:58
@zshamrock Docker itself can solve several use cases. This is why the `jboss/wildfly` image is meant to be really minimal, so we do not limit the number of use cases.

If you want to deploy your app to WildFly, our Docker image can help. As you wrote - you can extend the image by adding your custom configuration and your app. This way you'll have an environment that you are sure about it's stability. Additionally it's easy to move it around.

If you want to develop using the WildFly image - you can do this too - expose the management interfaces (and probably mount some volumes) if you want and you're ready to go.

Does it make clear a bit now?

**Comment by goldmann** [comment] 2015-02-21 14:02
BTW, this may shed some light on the configuration customization problem: https://goldmann.pl/blog/2014/07/23/customizing-the-configuration-of-the-wildfly-docker-image/

**Comment by goldmann** [comment] 2015-02-25 08:41
I fixed (in 8501f89295694c73980ed2edbb2f8053c775e041) the example in the "Extending the image" section which contains now the `CMD` that would start WildFly with properly bound management ports. Closing this, since I think it solves this issue. If you feel that this is not the right fix, please reopen and let me know.

**Closed by goldmann** 2015-02-25 08:41 UTC
